#!/bin/bash
verbose=true
blog_title="Blog of Blog"
blog_desc="Description blog to proof the power of blog."
blog_author="Jader Brasil"
blog_url="https://jaderebrasil.github.io/blog/"

max_postlist=4

public="../docs"

export github="https://github.com/jaderebrasil/blog"

# rewrite cleanf function of blog for a particular case
cleanf() {
	# Don't clean anything! except
	find "$blogdir/$public/posts" -name "*.html" -type f -exec rm -f {} +
	find "$blogdir/$public/category" -name "*.html" -type f -exec rm -f {} +
	rm -f $blogdir/$public/rss.xml
	rm -f $blogdir/$public/index.html
	rm -f $blogdir/$public/archive.html
}
